// src/services/ai/ai.brain.cycle.service.ts
//
// Orchestrates the full AI Brain daily cycle:
//   1. analyzeMarketplace
//   2. scanMarketplace
//   3. detectGrowthOpportunities
//   4. analyzeSellerPerformance
//   5. detectMarketplaceRisks
//
// Then generates a consolidated Markdown report.

import { analyzeMarketplace }        from "./ai.intelligence.service";
import { scanMarketplace }            from "./ai.scanner.service";
import { detectGrowthOpportunities } from "./ai.growth.service";
import { analyzeSellerPerformance }  from "./ai.seller.service";
import { detectMarketplaceRisks }    from "./ai.risk.service";
import { writeReport, todayStr, nowIso } from "./ai.fs.utils";

import type {
  MarketplaceIntelligence,
  ScanResult,
  GrowthReport,
  SellerIntelligence,
  RiskReport,
  BrainCycleResult,
} from "../../types/ai.types";

// ─────────────────────────────────────────────────────────
// Consolidated report builder
// ─────────────────────────────────────────────────────────

function buildDailyReport(
  date:          string,
  intelligence:  MarketplaceIntelligence | null,
  scan:          ScanResult | null,
  growth:        GrowthReport | null,
  sellers:       SellerIntelligence | null,
  risks:         RiskReport | null,
): string {
  const lines: string[] = [
    `# Flowjuyu AI Brain — Daily Report`,
    `## Date: ${date}`,
    "",
    `> Automatically generated by the Flowjuyu AI Brain Cycle`,
    `> Run timestamp: ${new Date().toLocaleString()}`,
    "",
    "---",
    "",
  ];

  // ── Intelligence ──────────────────────────────────────
  lines.push("## 📊 Marketplace Intelligence", "");
  if (intelligence) {
    lines.push(
      `| Metric | Value |`,
      `|--------|-------|`,
      `| Active products | ${intelligence.products_total} |`,
      `| Missing images | ${intelligence.products_without_images} |`,
      `| Without views | ${intelligence.products_without_views} |`,
      `| Inactive sellers | ${intelligence.inactive_sellers} |`,
      "",
      `### Trending Products (last 7 days)`,
      "",
    );
    if (intelligence.trending_products.length > 0) {
      intelligence.trending_products.slice(0, 5).forEach((p) => {
        lines.push(`- **${p.nombre}** — ${p.intention_count} intentions`);
      });
    } else {
      lines.push("_No trending products this period._");
    }
    lines.push("");

    lines.push(`### Trending Categories`, "");
    if (intelligence.trending_categories.length > 0) {
      intelligence.trending_categories.forEach((c) => {
        lines.push(`- **${c.nombre}** — ${c.intention_count} intentions`);
      });
    } else {
      lines.push("_No trending categories this period._");
    }
    lines.push("");
  } else {
    lines.push("_Intelligence analysis failed or skipped._", "");
  }

  lines.push("---", "");

  // ── Scanner ───────────────────────────────────────────
  lines.push("## 🔍 Marketplace Scan", "");
  if (scan) {
    lines.push(
      `**Issues found:** ${scan.issues.length}`,
      `**Tasks created:** ${scan.tasks_created}`,
      "",
    );
    scan.issues.forEach((issue) => {
      lines.push(
        `### [${issue.severity.toUpperCase()}] ${issue.title}`,
        "",
        `> ${issue.description}`,
        `> Affected: ${issue.count}`,
        "",
      );
    });
    if (scan.issues.length === 0) {
      lines.push("_No issues detected. Marketplace data quality is clean._", "");
    }
  } else {
    lines.push("_Scan failed or skipped._", "");
  }

  lines.push("---", "");

  // ── Growth ────────────────────────────────────────────
  lines.push("## 🚀 Growth Opportunities", "");
  if (growth && growth.opportunities.length > 0) {
    growth.opportunities.slice(0, 8).forEach((o, i) => {
      lines.push(
        `${i + 1}. **${o.type.replace(/_/g, " ")}** — ` +
        `${o.category ?? o.seller ?? ""}`,
        `   - Demand: ${o.demand_score} | Supply: ${o.supply_score}`,
        `   - _${o.suggestion}_`,
        "",
      );
    });
  } else {
    lines.push("_No significant growth opportunities detected._", "");
  }

  lines.push("---", "");

  // ── Sellers ───────────────────────────────────────────
  lines.push("## 🏪 Seller Intelligence", "");
  if (sellers) {
    lines.push(`### Top Sellers by Engagement`, "");
    sellers.top_sellers.slice(0, 5).forEach((s, i) => {
      lines.push(
        `${i + 1}. **${s.nombre_comercio}** — ` +
        `${s.intention_count} intentions, ${s.product_count} products`
      );
    });
    lines.push("");

    lines.push(`### Sellers Needing Attention`, "");
    if (sellers.risky_sellers.length > 0) {
      sellers.risky_sellers.slice(0, 5).forEach((s) => {
        lines.push(`- ⚠ **${s.nombre_comercio}** — ${s.product_count} products with data issues`);
      });
    } else {
      lines.push("_No risky sellers detected._");
    }
    lines.push("");

    lines.push(`### Inactive Sellers (30+ days)`, "");
    if (sellers.inactive_sellers.length > 0) {
      sellers.inactive_sellers.slice(0, 5).forEach((s) => {
        lines.push(`- **${s.nombre_comercio}** — last active: ${s.last_active ?? "unknown"}`);
      });
    } else {
      lines.push("_No inactive sellers found._");
    }
    lines.push("");
  } else {
    lines.push("_Seller analysis failed or skipped._", "");
  }

  lines.push("---", "");

  // ── Risks ─────────────────────────────────────────────
  lines.push("## 🚨 Risk Detection", "");
  if (risks) {
    lines.push(
      `**Risks found:** ${risks.risks.length}`,
      `**Auto-tasks created:** ${risks.tasks_created}`,
      "",
    );
    risks.risks.slice(0, 10).forEach((r) => {
      const emoji = r.severity === "critical" || r.severity === "high" ? "🔴" : "🟡";
      lines.push(`- ${emoji} [${r.severity.toUpperCase()}] ${r.description}`);
    });
    if (risks.risks.length === 0) {
      lines.push("_No marketplace risks detected._");
    }
    lines.push("");
  } else {
    lines.push("_Risk detection failed or skipped._", "");
  }

  lines.push(
    "---",
    "",
    `*Flowjuyu AI Brain — Brain Cycle Report — ${date}*`,
  );

  return lines.join("\n");
}

// ─────────────────────────────────────────────────────────
// Fault-tolerant step runner
// ─────────────────────────────────────────────────────────

async function runStep<T>(
  name: string,
  fn: () => Promise<T>
): Promise<T | null> {
  try {
    const result = await fn();
    return result;
  } catch (err) {
    console.error(`[brain] Step "${name}" failed:`, (err as Error).message);
    return null;
  }
}

// ─────────────────────────────────────────────────────────
// Public API
// ─────────────────────────────────────────────────────────

export async function runBrainCycle(): Promise<BrainCycleResult> {
  const startMs = Date.now();

  console.log("\n══════════════════════════════════════════");
  console.log("  FLOWJUYU AI BRAIN CYCLE — START");
  console.log("══════════════════════════════════════════\n");

  // Run all steps sequentially to avoid DB connection storms.
  // Each step is fault-tolerant: a failure returns null without
  // aborting the cycle.

  const intelligence = await runStep("intelligence", analyzeMarketplace);
  const scan         = await runStep("scanner",      scanMarketplace);
  const growth       = await runStep("growth",       detectGrowthOpportunities);
  const sellers      = await runStep("sellers",      analyzeSellerPerformance);
  const risks        = await runStep("risks",        detectMarketplaceRisks);

  // Write the consolidated daily report
  const date         = todayStr();
  const reportMd     = buildDailyReport(date, intelligence, scan, growth, sellers, risks);
  const reportFile   = await writeReport(`ai-report-${date}.md`, reportMd);

  const duration_ms  = Date.now() - startMs;

  const result: BrainCycleResult = {
    intelligence,
    scan,
    growth,
    sellers,
    risks,
    report_file: reportFile,
    duration_ms,
    ran_at:      nowIso(),
  };

  console.log("\n══════════════════════════════════════════");
  console.log(`  BRAIN CYCLE COMPLETE — ${duration_ms}ms`);
  console.log(`  Report: ${reportFile ?? "FAILED"}`);
  console.log("══════════════════════════════════════════\n");

  return result;
}
